[package]
name = "json-comments"
version = "0.1.0"
edition = "2021"

[lib]
name = "json_comments"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
# The fork of json-comments-rs that handles trailing commas
json-strip-comments = "3.1.0"
